
  # Deploy the new build to Openstack
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      # Ensure Openstack client is installed
      - name: Install OpenStack client
        run: |
            sudo apt-get install -y python3-openstackclient

      # Deploys to Openstack based on the specified values in the Github enviroment
      - name: Deploy to OpenStack
        env:
          OPENSTACK_AUTH: ${{ secrets.OPENSTACK_AUTH }}

        run: |
          
          # Extract authenticaiton from Github Secrets using the modified bash script for authenticaiton
          echo "$OPENSTACK_AUTH" > openstack_auth.sh
          source openstack_auth.sh

          # Update the cluster
          openstack stack update -t ${{env.CLUSTER_NAME}} \
            --parameter "key_name=" \
            --parameter "cluster_name=your_cluster_name" \
            --parameter "cluster_flavor=your_cluster_flavor" \
            --parameter "master_flavor=gx2.2c4r" \
            --parameter "node_count=1" \
            --parameter "image=flask-webserver" \
            skytjenester-cluster


