

name: CI/CD with OpenStack

on:
  push:
    branches:
      - main

jobs:

  # Install necessary packages for building and testing
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and test Flask app
        run: |
          # Replace these commands with your actual build and test commands
          python manage.py test

  # Deploy the new build to Openstack
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      # Ensure Openstack client is installed
      - name: Install OpenStack client
        run: |
            sudo apt-get install -y python3-openstackclient

      - name: Deploy to OpenStack
        env:
          OPENSTACK_AUTH: ${{ secrets.OPENSTACK_AUTH }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

        run: |
          
          # Extract authenticaiton from Github Secrets using the modified bash script for authenticaiton
          echo "$OPENSTACK_AUTH" > openstack_auth.sh
          source openstack_auth.sh

          # Build and push Docker images
          docker build -t ${{env.IMAGE_NAME}} .
          # docker build -t your-postgres-db ./postgres


      - name: Database migration
        run: |
          # Add commands to apply database migrations if needed
          docker exec -it your-flask-app flask db upgrade


