# Configmap which contains the enviroment variables for the application.
# (This is a simple example, in a real world scenario you would use a secret for this)
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  WEBSERVER_PORT: "80"

  DB_NAME: "skytjenesterdb"
  DB_USER: "postgres"
  DB_PASSWORD: ""

