heat_template_version: 2013-05-23

description: A Heat template for creating a Virtual machine capable of external communication through a public IP

# Enviroment variables for specifying server properties
parameters:
  key_name:
    type: string
    # default: {get_env: KEY_NAME}   
    default: skytjenester-2023
  image:
    type: string
    # default: {get_env: IMAGE_NAME}   
    default: fedora-coreos33-stable
  flavor:
    type: string
    # default: {get_env: FLAVOR}   
    default: gx2.1c1r

# Resources in the stack
resources:
  
  # The Virtual machine where the applicaiton is to be hosted
  server:
    type: OS::Nova::Server
    properties:
      key_name: {get_param: key_name}
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
        - network: {get_resource: network}

  # The network connected to the subnets for external communication
  network:
    type: OS::Neutron::Net

  # Subnet for communication between the instances internally
  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      cidr: '192.168.0.0/24'
      dns_nameservers: [ '129.241.0.200', '129.241.0.201' ]
      ip_version: 4
 
  # The Router used for communication between networks. In this case its the external gateway to the internet.
  router:  
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: ntnu-internal }
 
  # Interface to communicate between the subnet and the network through the Router
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: subnet }

  # The Security group which defines what type of communication is allowed through the network
  secgroup_generic:
    type: OS::Neutron::SecurityGroup
    properties:
      description: |
        a security group allowing users connect to the vm's using ssh
      rules:
       - protocol: icmp
         remote_ip_prefix: '0.0.0.0/0'
       - protocol: tcp
         port_range_min: 22
         port_range_max: 22
         remote_ip_prefix: '0.0.0.0/0'
       - protocol: tcp
         remote_ip_prefix: '192.168.0.0/24'
         port_range_min: 111
         port_range_max: 111
       - protocol: udp
         remote_ip_prefix: '192.168.0.0/24'
         port_range_min: 111
         port_range_max: 111
       - protocol: tcp
         remote_ip_prefix: '192.168.0.0/24'
         port_range_min: 2049
         port_range_max: 2049
       - protocol: udp
         remote_ip_prefix: '192.168.0.0/24'
         port_range_min: 2049
         port_range_max: 2049
       - protocol: tcp
         remote_ip_prefix: '192.168.0.0/24'
         port_range_min: 32767
         port_range_max: 32768
       - protocol: udp
         remote_ip_prefix: '192.168.0.0/24'
         port_range_min: 32767
         port_range_max: 32768
 